/**
 * API Types
 *
 * Type definitions matching the backend API schemas.
 * These types mirror the Pydantic models from the backend.
 */

/**
 * File upload information for sending to API
 */
export interface FileUpload {
  file_name: string;
  file_content: string; // Base64-encoded content
  file_type?: string; // MIME type
  file_size?: number; // Size in bytes
}

/**
 * Information about an uploaded file (from API response)
 */
export interface UploadedFileInfo {
  file_id: string;
  file_name: string;
  file_path: string;
  absolute_path: string;
  file_size: number;
  file_type?: string;
  uploaded_at: string; // ISO timestamp
}

/**
 * Input for creating a conversation message
 */
export interface ConversationInput {
  conversation_id: string; // UUID v4
  role: string; // 'user' | 'assistant' | 'system'
  message: string;
  files?: FileUpload[];
  metadata?: Record<string, any>;
  stream: boolean;
}

/**
 * Stream event types from the API
 */
export type StreamEventType =
  | 'files_processing'
  | 'files_uploaded'
  | 'text_delta'
  | 'pipeline_step_start'   // Pipeline node started
  | 'pipeline_step_complete'// Pipeline node finished
  | 'pipeline_step_failed'  // Pipeline node failed
  | 'artifact'              // Artifact generated by pipeline_artifacts_node
  | 'metadata'
  | 'message_complete'
  | 'error';

/**
 * What a timeline step represents, as classified by the backend.
 *
 * - 'agent'    — handoff to a specialist skill (user-facing work)
 * - 'pipeline' — a stage of the LC processing pipeline (user-facing work)
 * - 'tool'     — an internal orchestrator call such as load_skill. Machinery
 *                rather than work the user asked for, so it is not rendered in
 *                the timeline; see VISIBLE_STEP_KINDS.
 */
export type StepKind = 'agent' | 'pipeline' | 'tool';

/** Step kinds that earn a row in the ThinkingPanel. */
export const VISIBLE_STEP_KINDS: readonly StepKind[] = ['agent', 'pipeline'];

/**
 * Source of the streaming event
 */
export type StreamEventSource = 'orchestrator' | 'subagent';

/**
 * Metadata event types (nested inside metadata field)
 */
export type MetadataEventType = 'subagent_start' | 'subagent_complete' | 'step_update';

/**
 * Metadata structure for SSE events
 */
export interface EventMetadata {
  // For text_delta events (now at root level, not nested in metadata)
  source?: StreamEventSource; // 'orchestrator' | 'subagent'
  subagent?: string; // Name of the subagent
  node?: string; // LangGraph node name
  is_subagent?: boolean; // Whether message is from subagent

  // For metadata events (type: "metadata")
  event_type?: MetadataEventType; // 'subagent_start' | 'subagent_complete' | 'step_update'
  message?: string; // Message for subagent events

  // For step_update events
  updates?: Record<string, any>; // Internal state updates

  // Other metadata
  [key: string]: any;
}

/**
 * Pipeline step metadata attached to text_delta events from pipeline nodes.
 * Set via additional_kwargs in pipeline_nodes.py.
 */
export interface PipelineStepMetadata {
  pipeline_step?: string;       // "extraction" | "relationships" | "financial" | "regulations" | "advice"
  pipeline_final?: boolean;        // true for step 5 — route to main chat
  step_index?: number;             // 1-based
  [key: string]: any;
}

/**
 * Server-Sent Event for streaming responses.
 */
export interface ConversationStreamEvent {
  event: StreamEventType;

  conversationId?: string;

  // For text streaming (text_delta)
  role?: string;
  delta?: string;
  source?: StreamEventSource;
  node?: string;
  isSubagent?: boolean;
  metadata?: PipelineStepMetadata & EventMetadata; // pipeline tags + other metadata

  // For pipeline step lifecycle (pipeline_step_start / pipeline_step_complete / pipeline_step_failed)
  step?: string;      // stable id e.g. "extraction", or a skill name for a handoff
  stepIndex?: number; // 1-based
  totalSteps?: number;
  content?: string;   // step summary shown beneath the timeline row on completion
  label?: string;     // display name authored by the backend — render verbatim
  kind?: StepKind;    // what the step represents; drives whether it is shown at all

  // For file processing
  filesUploaded?: UploadedFileInfo[];

  // For completion
  messageId?: string;
  fullMessage?: string;

  // For errors
  error?: string;

  // For artifact events
  artifact?: ArtifactItem;
  artifactType?: ArtifactTypeValue;
}

/**
 * Non-streaming conversation response
 */
export interface ConversationResponse {
  conversation_id: string;
  message_id: string;
  role: string;
  message: string;
  uploaded_files?: UploadedFileInfo[];
  metadata?: Record<string, any>;
  created_at: string; // ISO timestamp
}

/**
 * API Error response
 */
export interface APIError {
  detail: string;
  status?: number;
}

/**
 * A single conversation entry from the list API
 */
export interface ConversationItem {
  id: string;
  firstMessage: string;
  isArchived: boolean;
  createdAt: string;
  updatedAt: string | null;
}

export interface PaginationMeta {
  total: number;
  page: number;
  perPage: number;
  totalPages: number;
  hasNext: boolean;
  hasPrev: boolean;
}

export interface ListConversationsResponse {
  status: string;
  data: ConversationItem[];
  meta: {
    pagination: PaginationMeta;
  };
}

/**
 * A single attachment reference stored on a message
 */
export interface AttachmentInfo {
  fileId: string;
  fileName: string;
  filePath: string;
  fileType?: string;
  downloadUrl?: string;
}

/**
 * Artifact type constants — mirrors backend ArtifactType
 */
export const ArtifactType = {
  LC_FORM_ADVISORY: 'lc_form_advisory',
} as const;

export type ArtifactTypeValue = typeof ArtifactType[keyof typeof ArtifactType];

/**
 * Human-readable button labels for each artifact type shown in the chat.
 */
export const ArtifactTypeLabel: Record<ArtifactTypeValue, string> = {
  lc_form_advisory: 'Review LC Form Advisory',
};

/**
 * Artifact status constants — mirrors backend ArtifactStatus
 */
export const ArtifactStatus = {
  PENDING: 'pending',
  GENERATING: 'generating',
  READY: 'ready',
  FAILED: 'failed',
} as const;

export type ArtifactStatusValue = typeof ArtifactStatus[keyof typeof ArtifactStatus];

/**
 * A single artifact attached to a message
 */
export interface ArtifactItem {
  id: string;
  messageId: string;
  conversationId: string;
  artifactType: ArtifactTypeValue;
  status: ArtifactStatusValue;
  data: Record<string, unknown> | null;
  error: string | null;
  createdAt: string;
  updatedAt: string | null;
}

/**
 * Request body for POST /messages/{messageId}/artifact
 */
export interface ArtifactGenerateRequest {
  conversationId: string;
  artifactType: ArtifactTypeValue;
}

/**
 * A single message from the history endpoint
 */
export interface ConversationMessageItem {
  id: string;
  role: 'user' | 'assistant';
  content: string | null;
  attachments: AttachmentInfo[] | null;
  artifacts: ArtifactItem[] | null;
  createdAt: string;
}

export interface ListConversationMessagesResponse {
  status: string;
  data: ConversationMessageItem[];
  meta: {
    pagination: PaginationMeta;
  };
}

/**
 * Response for POST /messages/{messageId}/artifact
 */
export interface ArtifactGenerateResponse {
  status: string;
  data: ArtifactItem;
}

// ─── Email Ticket Types ───────────────────────────────────────────────────────

export type EmailStatus = 'NEW' | 'IN_PROGRESS' | 'AWAITING_SEND' | 'RESOLVED' | 'CLOSED' | 'ARCHIVED';
export type EmailCategory =
  | 'LC_OPEN_REQUEST' | 'LC_AMENDMENT' | 'LC_PAYMENT'
  | 'BANK_TRANSFER' | 'ACCOUNT_INQUIRY' | 'LOAN_REQUEST'
  | 'TECHNICAL_SUPPORT' | 'CUSTOMER_SUPPORT' | 'BILLING_PAYMENT'
  | 'EDUCATION' | 'WORK_PROFESSIONAL' | 'PERSONAL'
  | 'COMMUNITY_NEWSLETTER' | 'COMMUNITY_FORUM' | 'MARKETING_PROMOTIONAL'
  | 'DOCUMENTATION_REQUEST' | 'COMPLIANCE_REGULATORY' | 'NOTIFICATION_ALERT'
  | 'SPAM_JUNK' | 'UNCATEGORIZED';
export type EmailPriority = 'LOW' | 'MEDIUM' | 'HIGH' | 'CRITICAL';
export type DraftStatus = string | null;

export interface EmailTicket {
  id: string;
  emailId: string;
  threadId: string;
  senderEmail: string;
  senderName: string;
  subject: string;
  category: EmailCategory;
  priority: EmailPriority;
  status: EmailStatus;
  draftStatus: DraftStatus;
  tags: string[] | null;
  isCommunityEmail: boolean;
  receivedAt: string;
  createdAt: string;
  updatedAt: string | null;
  // Detail-only fields (present in GET /tickets/:id)
  bodyText?: string;
  bodyHtml?: string;
  gmailLabelIds?: string[];
  attachments?: EmailAttachment[];
  draft?: EmailDraft | null;
  processedAt?: string | null;
  resolvedAt?: string | null;
}

export interface EmailAttachment {
  id: string;
  filename: string;
  contentType: string;
  fileSize: number;
}

export interface EmailDraft {
  id: string;
  toEmail: string;
  ccEmails: string[] | null;
  subject: string;
  // The backend may put HTML content in bodyText with bodyHtml null
  bodyText: string | null;
  bodyHtml: string | null;
  status: string;
  aiModel: string | null;
  agentNotes: string | null;
  editedBy: string | null;
  editedAt: string | null;
  sentAt: string | null;
  gmailMessageId: string | null;
  createdAt: string;
  updatedAt: string | null;
}

export interface ListTicketsParams {
  page?: number;
  size?: number;
  status?: EmailStatus | null;
  category?: EmailCategory | null;
  priority?: EmailPriority | null;
}

export interface ListTicketsResponse {
  status: string;
  data: EmailTicket[];
  message: string;
  errors: null | string;
  meta: {
    pagination: {
      total: number;
      page: number;
      perPage: number;
      totalPages: number;
      hasNext: boolean;
      hasPrev: boolean;
    };
  };
}
